### ISSUE TITLE
Not about this project

### ISSUE THREAD

**Issue by DevX-Cipher** [SeriousBuggie/XVehicles#7]
hey, mate, I was wondering if there is anywhere I can contact you please i would like to ask you a few questions about your 7zip plugin, please

**Comment by SeriousBuggie** [comment]
Discord: https://discord.gg/NVaNRXUvUU
Or forum: https://ut99.org/ut99.org/viewtopic.php?t=15014
Github: https://github.com/SeriousBuggie/7z-formatzzz
